server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/myblog?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
    druid:
#      最大连接数
      max-active: 20
#      初始化连接数
      initial-size: 5
#      最小连接数
      min-idle: 5
      max-wait: 1000
      stat-view-servlet:
        allow: 127.0.0.1
        login-username: admin
        login-password: Liss928520
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
#  热部署
  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
      enabled: true
    livereload:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lss.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis二级缓存
    cache-enabled: true
    #开启mybatis的字段命名驼峰转换
    map-underscore-to-camel-case: true
logging:
  file:
    name: /usr/local/log/myblog/myblog.log
  level:
    com.lss.dao : debug